# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 13:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('Status', models.CharField(default='outdated', max_length=100)),
                ('AppVersion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('showid', models.CharField(max_length=50)),
                ('showname', models.CharField(max_length=100)),
                ('show', models.BooleanField(default=True)),
                ('newep', models.BooleanField(default=False)),
                ('poster', models.CharField(default='', max_length=300)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('count', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('body', models.TextField()),
                ('state', models.IntegerField(default=0)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),

        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id',
                 models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoplaybest', models.BooleanField(default=False)),
                ('last_activity', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('night_mode', models.BooleanField(default=False)),
                ('autoplaynext', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='watched',
            fields=[
                ('id',
                 models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('epid', models.CharField(max_length=50)),
                ('epname', models.CharField(max_length=100)),
                ('showid', models.CharField(max_length=50)),
                ('showname', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
