# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkGrabberDjango', '0002_favourite_featurerequest_post_profile_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.IntegerField(),
        ),
    ]
